/**
 * Post API
 * API documentation for Post
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiExceptionDto { 
    statusCode?: number;
    message?: string;
    status?: string;
    error?: string;
    errors?: object;
    timestamp?: string;
    path?: string;
    stack?: string;
}

