/**
 * Post API
 * API documentation for Post
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommentDto } from './commentDto';
import { UserInformationDto } from './userInformationDto';


export interface PostDto { 
    id: string;
    createdAt: string;
    updatedAt: string;
    text: string;
    author: UserInformationDto;
    comments: Array<CommentDto>;
    commentsCount: number;
    likedBy: Array<UserInformationDto>;
    likedByCount: number;
}

