/**
 * Post API
 * API documentation for Post
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserInformationDto { 
    id: string;
    username: string;
    email: string;
    name: string;
    avatarUrl: string;
    bio: string;
    location: string;
}

